name: "Windows 7 x86"
on:
  push:
    branches:
      - windows7
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: 'Git Clone'
        shell: cmd
        run: |
          mkdir C:\onnxruntime
          git clone -b windows7 --single-branch https://github.com/xzmzm/onnxruntime.git C:\onnxruntime
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.x'
          architecture: 'x64'
      - run: Get-PSDrive
      # - name: 'Delete .git'
        # shell: cmd
        # run: |
          # rmdir /s /q ${{ github.workspace }}\.git
      - name: 'Build and Test'
        working-directory: C:\onnxruntime
        run: |
          python C:/onnxruntime/tools/ci_build/build.py --build_dir C:\onnxruntime\build\windows_x86 --x86 --enable_msvc_static_runtime --build_shared_lib --enable_onnx_tests --ms_experimental --use_dml --use_winml --cmake_generator "Visual Studio 17 2022" --config Release --compile_no_warning_as_error --enable_lto --disable_rtti --enable_wcos --parallel --cmake_extra_defines CMAKE_SYSTEM_VERSION=10.0.19041.0
      - name: 'Upload Release Files'
        uses: actions/upload-artifact@v3
        with:
          name: release_files_x86
          path: C:\onnxruntime\build\windows_x86\Release\Release